# Generated by Django 4.2.6 on 2023-11-06 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place')),
                ('time_to_act', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('is_pleasant', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is_pleasant')),
                ('frequency', models.DurationField(default=datetime.timedelta(days=1), verbose_name='frequency')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reward')),
                ('time_to_complete', models.DurationField(blank=True, default=datetime.timedelta(seconds=120), null=True, verbose_name='time_to_complete')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is_public')),
                ('last_execution', models.DateField(blank=True, null=True, verbose_name='last_execution')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.habit', verbose_name='Pleasant habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
